env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    binary: auto-sign
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    ids:
      - auto-sign
    image_templates:
      - "hb0730/auto-sign:latest"
      - "hb0730/auto-sign:{{.Tag}}"
    skip_push: false
    dockerfile: Dockerfile
    use_buildx: true
    extra_files:
      - config

archives:
  - id: tar
    format: tar.gz
    replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip