geekhub:
  cookies:
    _session_id:
appletuan:
  cookies:
    _session_id:
ld246:
  user:
    username:
    password:
v2ex:
  cookies:
    PB3_SESSION:
    A2:
famijia:
  headers:
    token:
    black_box:
    device_id:
chinaG:
  user:
    username:
    password:
cron:
  geekhub: "0 7 * * *"
  appletuan: "40 7 * * *"
  ld246: "5 0 * * *"
  v2ex: "0 8 * * *"
  famijia: "10 8 * * *"
  chinag: "20 8 * * *"
message:
  enabled: true
  type: "bark"
  bark:
    url:
    key:
  mail:
    host: "smtp.qq.com"
    protocol: "smtp"
    port: 465
    username:
    password:
    from_name: "auto-sign"
    to: