geekhub:
  cookies:
    _session_id:
appletuan:
  cookies:
    _session_id:
ld246:
  user:
    username:
    password:
v2ex:
  cookies:
    PB3_SESSION:
    A2:
famijia:
  headers:
    token:
    deviceId:
    blackBox:
chinaG:
  user:
    url:
    username:
    password:
pagodaWxMini:
  url:
  headers:
    userToken:
cron:
  ld246: "0 7 * * *"
  geekhub: "10 7 * * *"
  appletuan: "20 7 * * *"
  v2ex: "0 8 * * *"
  famijia: "10 8 * * *"
  chinaG: "20 8 * * *"
  pagodaWxMini: "30 8 * * *"
message:
  enabled: true
  type: "bark"
  bark:
    url:
    key:
  mail:
    host:
    protocol:
    port: 465
    username:
    password:
    from_name:
    to: