geekhub:
  cookies:
    _session_id:
ld246:
  user:
    userName:
    password:
v2ex:
  cookies:
    PB3_SESSION:
    A2:
cron:
  geekhub: "5 0 * * *"
  ld246: "3 0 * * *"
  v2ex: "5 8 * * *"

email:
  host:
  protocol:
  port:
  username:
  password:
  fromName:
  to: