cron:
  geekhub: "0 7 * * *"
  appletuan: "40 7 * * *"
  ld246: "5 0 * * *"
  v2ex: "0 8 * * *"
  famijia: "10 8 * * *"
  chinaG: "20 8 * * *"
geekhub:
  cookies:
    _session_id:
appletuan:
  cookies:
    _session_id:
ld246:
  user:
    username:
    password:
v2ex:
  cookies:
    A2:
    PB3_SESSION:
famijia:
  headers:
    token:
    black_box:
    device_id:
chinaG:
  user:
    username:
    password:
message:
  enabled: true
  type: bark
  bark:
    url:
    key:
  mail:
    host:
    protocol:
    port: 465
    username:
    password:
    from_name:
    to:
