name: Gitee repos mirror periodic job
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 1 * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee
        uses: Yikun/gitee-mirror-action@v0.10
        with:
          src: github/hb0730
          dst: gitee/hb0730
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
