name: Go
on: [ push,pull_request ]
jobs:
  build:
    name: Build with go ${{matrix.go_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go_version: [ 1.15 ]
        os: [ windows-latest,ubuntu-latest,macos-latest ]
    steps:
      - name: Set up Go ${{matrix.go_version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go_version}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          go build -a -o auto-sign main.go
          ls
      - name: zip
        run: |
          mkdir auto-sign-${{matrix.os}}
          cp auto-sign auto-sign-${{matrix.os}}
          zip auto-sign-${{matrix.os}}.zip auto-sign-${{matrix.os}}
          ls