name: Go
on: [ push,pull_request ]
jobs:
  build:
    name: Build with go ${{matrix.go_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    outputs:
      auto-sign: ${{steps.set-version.outputs.auto-sign}}
    strategy:
      matrix:
        go_version: [ 1.15 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Set up Go ${{matrix.go_version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go_version}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          go build .
          ls
      - name: release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "auto-sign*"
          delete_file: "auto-sign*"
          tags: true
          draft: false
          overwrite: true
  image:
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{contains(github.ref,'tags')}}
    steps:
      - name: tag
        id: tag
        run: |
          version=${{github.ref}}
          tag= basename $version
          echo "AUTO_VERSION=$(echo $tag)" >> $GITHUB_ENV
          echo ::set-output name=AUTO_VERSION::$(basename $version)
          echo ${{steps.tag.outputs.AUTO_VERSION}}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{steps.tag.outputs.AUTO_VERSION}}
          tags: |
            hb0730/auto-sign:latest
            hb0730/auto-sign:${{steps.tag.outputs.AUTO_VERSION}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
