name: Go
on: [ push,pull_request ]
jobs:
  build:
    name: Build with go ${{matrix.go_version}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        go_version: [ 1.15 ]
        os: [ windows-latest,ubuntu-latest,macos-latest ]
    steps:
      - name: Set up Go ${{matrix.go_version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go_version}}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build
        run: |
          go build -a -o .
          ls
  release:
    name: Release
    nedds: build
    runs-on: [ ubuntu-latest ]
    steps:
      - name: release
        uses: xresloader/upload-to-github-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "auto-sign*"
          delete_file: "auto-sign*"
